//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class OO7_Group
    {
        public int Id { get; set; }
        public string Author { get; set; }
        public Nullable<int> Times { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTime> PubDate { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
