//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class P_ChinesePractice
    {
        public int id { get; set; }
        public string word { get; set; }
        public string pinyin { get; set; }
        public Nullable<int> todayIndex { get; set; }
        public Nullable<System.DateTime> crateDate { get; set; }
        public Nullable<int> sucess { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
