//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeachUnit
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public int TeachId { get; set; }
        public string EncryptStr { get; set; }
        public string TimeMillis { get; set; }
        public string ClassName { get; set; }
        public string TeachUnitName { get; set; }
        public string AttendClassTime { get; set; }
        public string PlayWebCastId { get; set; }
        public string Provider { get; set; }
        public string Webroot { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
