//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int Id { get; set; }
        public string isVip { get; set; }
        public string UserId { get; set; }
        public string mobile { get; set; }
        public string sex { get; set; }
        public string signature { get; set; }
        public string username { get; set; }
        public string nickname { get; set; }
        public string userMarkList { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
    }
}
