//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZiKaoEntities : DbContext
    {
        public ZiKaoEntities()
            : base("name=ZiKaoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Subject> Subject { get; set; }
        public virtual DbSet<TCore> TCore { get; set; }
        public virtual DbSet<TIssue> TIssue { get; set; }
        public virtual DbSet<TIssueSubject> TIssueSubject { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<VipUsers> VipUsers { get; set; }
        public virtual DbSet<Topic> Topic { get; set; }
    }
}
